I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rpcsEngine.rpy", line 79, in script
    if groundtaken >= 20 and foresttribe == False:
  File "game/rpcsEngine.rpy", line 79, in <module>
    if groundtaken >= 20 and foresttribe == False:
NameError: name 'foresttribe' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rpcsEngine.rpy", line 79, in script
    if groundtaken >= 20 and foresttribe == False:
  File "E:\Coding\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "E:\Coding\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\Coding\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/rpcsEngine.rpy", line 79, in <module>
    if groundtaken >= 20 and foresttribe == False:
NameError: name 'foresttribe' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
testground 1.0
Sun Jun  4 23:28:23 2023
